json.posts ams(@posts, scope: current_user)
json.blocks ams(@blocks)
json.pictures ams(@pictures)
json.paragraphs ams(@paragraphs)
json.visibilities ams(@visibilities)
json.pins ams(@pins)
json.stories ams(@stories, scope: @company)
json.posts_stories ams(@posts_stories)
