json.(pin, :uuid, :user_id, :parent_id, :pinboard_id)
json.(pin, :pinnable_id, :pinnable_type)
json.(pin, :content, :origin)
json.(pin, :pins_count)
json.(pin, :is_approved)
json.(pin, :created_at, :updated_at)
